#!/usr/bin/python

import sys
from subprocess import call

if sys.argv[1] == "list":
    call(["/usr/bin/parts_extract", "-l", sys.argv[2]])
elif sys.argv[1] == "copyout":
    call(["/usr/bin/parts_extract", "-l", sys.argv[2], "--mc_file", sys.argv[3], "--mc_dest_file", sys.argv[4]])
else:
    exit(1)

exit (0)
